### ISSUE TITLE
BOM and CPL files no longer valid for JLCPCB SMT quoting

### ISSUE THREAD

**Issue by GuySmiley14** [damienmaguire/Tesla-Front-Drive-Unit#4]
Recently JLCPCB has changed the headers in their BOM and CPL files to use the term "Footprint" instead of "Package". The current files produce this error on upload:

![Screenshot 2021-10-07 at 02-39-02 PCB Prototype PCB Fabrication Manufacturer - JLCPCB](https://user-images.githubusercontent.com/8140532/136349991-6ae38620-5d2e-4784-b438-768ee68d9669.png)

**Comment by damienmaguire** [comment]
Yep saw that thanks.
